'use client';

import type { Sublemma } from '@/ai/flows/llm-proof-decomposition';
import type { ExploreArtifacts } from '@/ai/exploration-assistant/exploration-assistant.schemas';
import type { Message } from '@/components/chat/interactive-chat';
import type { GraphData } from '@/components/proof-graph';
import type { ArtifactReviewResult, ExtractedArtifact } from '@/types/review';

export type View = 'home' | 'explore' | 'workspace' | 'proof';

// Extended ProofVersion to support raw vs structured versions, numbering and metadata
export type ProofVersion = {
  id: string;
  type: 'raw' | 'structured';
  versionNumber: string; // e.g. "1" or "2.1"
  baseMajor: number; // major raw version this structured version belongs to
  sublemmas: Sublemma[];
  // Optional raw/serialized content for this version
  content?: string;
  // Optional structured payload (lightweight summary)
  structured?: {
    provedStatement?: string;
    normalizedProof?: string;
  };
  // Flags
  userEdited?: boolean; // true when user explicitly edited this version
  derived?: boolean; // true when auto-generated by decomposition
  timestamp: Date;
  /** Whole-proof analysis result (existing footer). */
  validationResult?: ProofValidationResult;
  /** Per-step analysis results keyed by 0-based step index. */
  stepValidation?: Record<number, ProofValidationResult>;
  /** Which step was last edited (for contextual CTA). */
  lastEditedStepIdx?: number | null;
  graphData?: GraphData;
  /** Hash used to dedupe graph generation for identical structured step sets. */
  graphHash?: string;
};

export type PendingSuggestion = {
  suggested: string; // model-proposed final statement
  variantType: 'WEAKENING' | 'OPPOSITE';
  provedStatement: string; // extracted from raw proof decomposition
  sublemmas: Sublemma[]; // pre-decomposed steps for instant accept
  explanation: string;
  normalizedProof?: string; // full normalized proof text for fallback rendering
  rawProof?: string; // original raw proof text for fallback rendering
};

export type ProofValidationResult = {
  isError?: boolean;
  isValid?: boolean;
  feedback: string;
  timestamp: Date;
  model?: string;
  /** Used to prevent re-running analysis when the underlying proof input is unchanged. */
  sourceType?: 'raw' | 'structured';
  /** Hash of the proof input (raw text or structured steps) for de-duping. */
  sourceHash?: string;
};

export type StoreData = {
  view: View;
  /** Where to return when leaving Workspace (so we don't reset Proof/Explore state). */
  lastViewBeforeWorkspace: View | null;
  problem: string | null;
  lastProblem: string | null;
  messages: Message[];

  /** Cancel the current in-flight Proof chat (right sidebar) streaming request (if any). */
  cancelChatCurrent?: (() => void) | null;

  /** Draft text prefilled into the proof-mode chat input (used by global selection toolbar). */
  chatDraft: string;
  /** Bumped to request focus/apply of chatDraft. */
  chatDraftNonce: number;

  /** Draft text prefilled into the explore-mode chat input (used by global selection toolbar). */
  exploreDraft: string;
  /** Bumped to request focus/apply of exploreDraft. */
  exploreDraftNonce: number;

  // Explore mode
  /** Whether the user has ever entered Explore in this session (used for "Continue exploring" CTA). */
  exploreHasSession: boolean;
  exploreSeed: string | null;
  exploreMessages: Message[];
  exploreArtifacts: ExploreArtifacts | null;
  /**
   * User edits overlay for extracted artifacts.
   * Keyed by the original extracted string -> edited string.
   */
  exploreArtifactEdits: {
    candidateStatements: Record<string, string>;
    /**
     * Non-statement artifacts are scoped per candidate statement (keyed by the original statement string).
     */
    perStatement: Record<
      string,
      {
        assumptions: Record<string, string>;
        examples: Record<string, string>;
        counterexamples: Record<string, string>;
      }
    >;
  };
  exploreTurnId: number;
  cancelExploreCurrent?: (() => void) | null;

  loading: boolean;
  error: string | null;
  errorDetails: string | null;
  errorCode: string | null;
  isChatOpen: boolean;
  /** Prove-mode chat panel width (px). Used for desktop resizable right sidebar. */
  proofChatPanelWidth: number;
  isHistoryOpen: boolean;
  viewMode: 'raw' | 'structured' | 'graph';
  proofHistory: ProofVersion[];

  // Raw proof + background decomposition state
  rawProof: string;
  /** Incremented to request that the Raw Proof editor enters editing mode + focuses. */
  rawProofEditNonce: number;
  attemptSummary: {
    status: 'PROVED_AS_IS' | 'PROVED_VARIANT' | 'FAILED';
    finalStatement: string | null;
    variantType: 'WEAKENING' | 'OPPOSITE' | null;
    explanation: string;
  } | null;
  isDecomposing: boolean;
  decomposeError: string | null;
  stepsReadyNonce: number;
  decomposeMeta: { provedStatement: string; normalizedProof: string } | null;
  /** The raw proof text that the latest decomposition corresponds to (used to know whether steps are up-to-date). */
  decomposedRaw: string | null;
  activeVersionIdx: number;
  pendingSuggestion: PendingSuggestion | null;
  pendingRejection: { explanation: string } | null;
  // Streaming progress
  progressLog: string[];
  /** Monotonic run id for the current proof attempt. Used to ignore late callbacks after cancel/restart. */
  proofAttemptRunId: number;
  // Cancel the current in-flight streaming request (if any)
  cancelCurrent?: (() => void) | null;
  // Live draft streaming (token-level)
  liveDraft: string;
  isDraftStreaming: boolean;

  /** KaTeX macros used for rendering in Prover mode (typically carried over from Workspace). */
  proofRenderMacros: Record<string, string>;

  // Whole-proof analysis UI state
  isAnalyzingProof: boolean;
  analyzeProofRunId: number;

  // Workspace (single-file editor + per-selection threads)
  workspaceDoc: string;
  workspaceMessages: Message[];
  /** Draft text prefilled into the workspace chat input (used by selection toolbar). */
  workspaceDraft: string;
  workspaceDraftNonce: number;
  isWorkspaceChatOpen: boolean;
  workspaceRightPanelTab: 'chat' | 'insights' | 'preview' | 'review';
  workspaceRightPanelWidth: number; // px

  // Workspace Review mode (theorem-like LaTeX artifacts)
  workspaceReviewArtifacts: ExtractedArtifact[];
  /** Keyed by label (preferred) else `type@startChar`. */
  workspaceReviewEdits: Record<string, { statement: string; proof?: string | null }>;
  workspaceReviewResults: Record<string, ArtifactReviewResult>;

  // Workspace Insights (Explore-style artifacts)
  workspaceArtifacts: ExploreArtifacts | null;
  workspaceInsightsIsExtracting: boolean;
  workspaceArtifactEdits: {
    candidateStatements: Record<string, string>;
    perStatement: Record<
      string,
      {
        assumptions: Record<string, string>;
        examples: Record<string, string>;
        counterexamples: Record<string, string>;
      }
    >;
  };
  workspaceTurnId: number;
  cancelWorkspaceCurrent?: (() => void) | null;
  /** Cancel the current in-flight Workspace chat streaming request (if any). */
  cancelWorkspaceChatCurrent?: (() => void) | null;
};

export interface AppState extends StoreData {
  reset: () => void;

  /** Cancel an in-flight proof attempt and restore a consistent non-loading UI state. */
  cancelProofAttempt: () => void;

  /** Navigate back to homepage without clearing current workspace/proof state. */
  goHome: () => void;

  /** Prefill + focus the proof-mode chat input (and optionally open the chat panel). */
  setChatDraft: (text: string, opts?: { open?: boolean }) => void;

  /** Prefill + focus the explore-mode chat input. */
  setExploreDraft: (text: string) => void;

  /** Set/cancel the in-flight Proof chat stream. */
  setChatCancelCurrent: (cancel: (() => void) | null) => void;

  // Workspace actions
  startWorkspace: (seed?: string) => void;
  newWorkspace: () => void;
  /** Navigate to Workspace from the current view, optionally appending a snippet to the document. */
  goToWorkspace: (opts?: { from?: View; append?: string }) => void;
  /** Return from Workspace to the previously active view (typically Proof/Explore). */
  returnFromWorkspace: () => void;
  setWorkspaceDoc: (doc: string) => void;
  setWorkspaceDraft: (text: string, opts?: { open?: boolean }) => void;
  setWorkspaceMessages: (updater: ((prev: Message[]) => Message[]) | Message[]) => void;
  setIsWorkspaceChatOpen: (open: boolean | ((prev: boolean) => boolean)) => void;
  setWorkspaceRightPanelTab: (tab: 'chat' | 'insights' | 'preview' | 'review') => void;
  setWorkspaceRightPanelWidth: (widthPx: number) => void;

  // Workspace Review actions
  setWorkspaceReviewArtifacts: (items: ExtractedArtifact[]) => void;
  setWorkspaceReviewEdit: (
    key: string,
    edits: { statement: string; proof?: string | null },
  ) => void;
  resetWorkspaceReviewEdits: (key?: string) => void;
  applyWorkspaceReviewEditsToDoc: (key: string) => void;
  /** Set to null to clear the stored result for this key. */
  setWorkspaceReviewResult: (key: string, result: ArtifactReviewResult | null) => void;

  // Workspace Insights actions
  setWorkspaceArtifacts: (artifacts: ExploreArtifacts | null) => void;
  setWorkspaceInsightsExtracting: (extracting: boolean) => void;
  deleteWorkspaceCandidateStatement: (statement: string) => void;
  setWorkspaceArtifactEdit: (opts: {
    kind: 'candidateStatements' | 'assumptions' | 'examples' | 'counterexamples';
    statementKey?: string;
    original: string;
    edited: string;
  }) => void;
  bumpWorkspaceTurnId: () => number;
  getWorkspaceTurnId: () => number;
  setWorkspaceCancelCurrent: (cancel: (() => void) | null) => void;

  /** Set/cancel the in-flight Workspace chat stream (separate from Insights extraction). */
  setWorkspaceChatCancelCurrent: (cancel: (() => void) | null) => void;

  // Explore navigation / state
  startExplore: (seed?: string) => void;
  /** Reset Explore into a fresh empty session and switch to Explore view. */
  newExplore: () => void;
  setExploreMessages: (updater: ((prev: Message[]) => Message[]) | Message[]) => void;
  setExploreArtifacts: (artifacts: ExploreArtifacts | null) => void;
  deleteExploreCandidateStatement: (statement: string) => void;
  setExploreArtifactEdit: (opts: {
    kind: 'candidateStatements' | 'assumptions' | 'examples' | 'counterexamples';
    /** Candidate statement key for non-candidate edits. */
    statementKey?: string;
    original: string;
    edited: string;
  }) => void;
  clearExploreArtifactEdits: () => void;
  bumpExploreTurnId: () => number;
  getExploreTurnId: () => number;
  setExploreCancelCurrent: (cancel: (() => void) | null) => void;
  startExploreFromFailedProof: () => void;

  startProof: (problem: string, opts?: { force?: boolean }) => Promise<void>;
  /** Restore the current Proof view without starting a new run. */
  resumeProof: () => void;
  retry: () => Promise<void>;
  editProblem: () => void;
  setMessages: (updater: ((prev: Message[]) => Message[]) | Message[]) => void;

  // Variant handling
  acceptSuggestedChange: () => void;
  clearSuggestion: () => void;
  clearRejection: () => void;

  // UI actions
  setIsChatOpen: (open: boolean | ((prev: boolean) => boolean)) => void;
  setProofChatPanelWidth: (widthPx: number) => void;
  setIsHistoryOpen: (open: boolean | ((prev: boolean) => boolean)) => void;
  setViewMode: (mode: 'raw' | 'structured' | 'graph') => void;
  toggleStructuredView: () => void;

  /** Run whole-proof analysis for the current view (raw or structured). No-op in graph view. */
  analyzeCurrentProof: () => Promise<void>;

  /** Cancel an in-flight analysis run (best-effort: ignores late results). */
  cancelAnalyzeCurrentProof: () => void;

  // Raw proof
  setRawProof: (raw: string) => void;
  runDecomposition: () => Promise<void>;

  /** Request that the Raw Proof editor enters editing mode (focus textarea). */
  requestRawProofEdit: () => void;

  // Version helpers (used by UI)
  getCurrentRawBaseMajor: () => number | null;
  hasUserEditedStructuredForBaseMajor: (baseMajor: number) => boolean;
  hasUserEditedStructuredForCurrentRaw: () => boolean;

  /** Snapshot a manual edit to a structured proof as a new structured minor version (N.k+1). */
  snapshotStructuredEdit: (updates: Partial<ProofVersion>) => void;

  /** Ensure graphData exists for a structured proof version (silent + deduped). */
  ensureGraphForVersion: (versionId: string) => Promise<void>;

  // Proof version management
  setActiveVersionIndex: (index: number) => void;
  addProofVersion: (version: Omit<ProofVersion, 'timestamp'>) => void;
  updateCurrentProofVersion: (updates: Partial<ProofVersion>) => void;
  /**
   * Update non-versioned metadata for the currently active proof version.
   *
   * This is intended for ephemeral data like validation results and graph data.
   * It MUST NOT append a new proof version.
   */
  updateCurrentProofMeta: (updates: Partial<ProofVersion>) => void;
  updateCurrentStepValidation: (opts: {
    stepIndex: number;
    result?: ProofValidationResult;
  }) => void;
  clearLastEditedStep: () => void;

  /**
   * Delete a proof version by id.
   *
   * Deletion rules:
   * - Deleting a raw version deletes all versions for that baseMajor.
   * - Deleting a structured version deletes only that entry, unless it's the only
   *   structured version for that baseMajor (in which case we delete the entire group).
   */
  deleteProofVersion: (id: string) => void;

  // Navigation
  goBack: () => void;

  proof: () => ProofVersion;
}
